import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@context/AuthContext";
import SnackProvider from "@context/SnackbarContext";
import Navbar from "@components/navbar/Navbar";
import NavbarProvider from "@context/NavbarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js"></script>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <NavbarProvider>
            <SnackProvider>
              <Navbar />
              {children}
            </SnackProvider>
          </NavbarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
